---
abstract: 'File finder using Path::Class'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Config: 0
  Exporter: 0
  File::Copy: 0
  File::Find: 0
  File::Temp: 0
  File::pushd: 0
  Test::Deep: 0
  Test::More: 0.92
  autodie: 0
  parent: 0
  perl: 5.010
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Class-Rule
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Path::Class::Rule:
    file: lib/Path/Class/Rule.pm
    version: 0.005
requires:
  Carp: 0
  List::Util: 0
  Number::Compare: 0.02
  Path::Class: 0
  Scalar::Util: 0
  Text::Glob: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  perl: 5.010
  re: 0
  strict: 0
  warnings: 0
  warnings::register: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Path-Class-Rule
  homepage: http://github.com/dagolden/path-class-rule
  repository: http://github.com/dagolden/path-class-rule
version: 0.005
