---
abstract: 'File finder using Path::Class'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Config: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  File::pushd: 0
  Path::Class: 0
  Test::Deep: 0
  Test::More: 0.92
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Class-Rule
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Path::Class::Rule:
    file: lib/Path/Class/Rule.pm
    version: 0.012
requires:
  Carp: 0
  Data::Clone: 0
  List::Util: 0
  Number::Compare: 0.02
  Path::Class::Dir: 0
  Scalar::Util: 0
  Text::Glob: 0
  Try::Tiny: 0
  perl: 5.010
  re: 0
  strict: 0
  warnings: 0
  warnings::register: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Path-Class-Rule
  homepage: https://metacpan.org/release/Path-Class-Rule
  repository: git://github.com/dagolden/path-class-rule.git
version: 0.012
